from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from cogsol.management.base import BaseCommand

MANAGE_PY = """\
#!/usr/bin/env python
import sys
from pathlib import Path

from cogsol.core.management import execute_from_command_line


def main():
    project_path = Path(__file__).resolve().parent
    execute_from_command_line(sys.argv, project_path=project_path)


if __name__ == "__main__":
    main()
"""

SETTINGS_PY = """\
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
PROJECT_NAME = "{project_name}"
AGENTS_APP = "agents"
"""

TOOLS_PY = """\
from cogsol.tools import BaseTool, tool_params


class ExampleTool(BaseTool):
    description = "Demo tool that echoes the provided text."

    @tool_params(
        text={"description": "Text to echo", "type": "string", "required": True},
        count={"description": "Times to repeat", "type": "integer", "required": False},
    )
    def run(self, chat=None, data=None, secrets=None, log=None, text: str = "", count: int = 1):
        \"\"\"
        text: Text to echo back.
        count: Times to repeat the text.
        \"\"\"
        message = " ".join([text] * max(1, int(count)))
        # chat/data/secrets/log are available per platform docs
        response = message
        return response
"""

LESSONS_PY = """\
from cogsol.tools import BaseLesson


class ExampleLesson(BaseLesson):
    name = "ExampleLesson"
    content = "Sample reusable context that is only used when relevant."
"""

FAQS_PY = """\
from cogsol.tools import BaseFAQ


class ExampleFAQ(BaseFAQ):
    question = "How do I use this project?"
    answer = "Update agents.py and tools.py with your own logic."
"""

FIXED_RESPONSES_PY = """\
from cogsol.tools import BaseFixedResponse


class ExampleFixedResponse(BaseFixedResponse):
    key = "fallback"
    response = "Thanks for trying CogSol!"
"""

README = """\
# {project_name}

Generated by `cogsol-admin startproject`.

- Create agents with `python manage.py startagent MyAgent` (per-agent folders under `agents/`).
- Define reusable tools in `agents/tools.py` and import them in each agent.
- Run `python manage.py makemigrations` to capture changes.
- Run `python manage.py migrate` to sync with CogSol APIs.
"""


class Command(BaseCommand):
    requires_project = False
    help = "Create a new CogSol project skeleton."

    def add_arguments(self, parser):
        parser.add_argument("name", help="Project name (also used as directory name).")
        parser.add_argument(
            "directory",
            nargs="?",
            help="Optional destination directory. Defaults to the project name.",
        )

    def handle(self, project_path: Path | None, **options: Any) -> int:
        name = str(options.get("name") or "")
        directory = options.get("directory")
        target_dir = Path(directory or name).resolve()
        if target_dir.exists() and any(target_dir.iterdir()):
            print(f"Destination {target_dir} is not empty.")
            return 1

        target_dir.mkdir(parents=True, exist_ok=True)
        (target_dir / "agents").mkdir(parents=True, exist_ok=True)
        (target_dir / "agents" / "migrations").mkdir(parents=True, exist_ok=True)

        files = {
            "manage.py": MANAGE_PY,
            "settings.py": SETTINGS_PY.format(project_name=name),
            "agents/__init__.py": "",
            "agents/tools.py": TOOLS_PY,
            "agents/migrations/__init__.py": "",
            "README.md": README.format(project_name=name),
            ".env.example": "COGSOL_ENV=local\nCOGSOL_API_BASE=http://localhost:8000\n# Optional: COGSOL_API_TOKEN=your-token\n",
        }

        for relative_path, content in files.items():
            target_file = target_dir / relative_path
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(textwrap.dedent(content), encoding="utf-8")

        print(f"Created CogSol project '{name}' at {target_dir}")
        return 0
